version: '3'
services:
  spring_app:
    container_name: ems_server
    platform: linux/amd64
    image: drewm20/spring_app:1.0.0
    build: .
    ports:
      - 8080:8080
    env_file:
      - app.env
    depends_on:
      - database

  database:
    container_name: ems_database
    image: "postgres:15.2-bullseye"
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
